### ISSUE TITLE
Great project. Thanks for sharing. I'll give it a go capturing a scene. It would be phantasmic to have a viewer for Unity 3D

### ISSUE THREAD

**Issue by volkerku** [cr333/OmniPhotos#1]
Great project. Thanks for sharing. I'll give it a go capturing a scene. It would be phantasmic to have a viewer for Unity 3D

**Comment by cr333** [comment]
Thanks a lot for interest and enthusiasm! :)

It should definitely be possible to build an OmniPhotos viewer with Unity and we welcome additional viewer implementations. One can probably reuse or adapt our shaders, which should make the implementation a bit easier.

However, I’m afraid that this is out of the scope of our research project.
